### ISSUE TITLE
Add decompression to V2

### ISSUE THREAD

**Issue by stoddabr** [nats-io/nats-spark-connector#27]
### What motivated this proposal?

I am working on a project which ingests data from a stream compressed with zlib. The load_balanced code was great since it supported this feature from this commit https://github.com/nats-io/nats-spark-connector/commit/2f6314d17fab56ba4887509a76fc3b03154d61d7. However, we want to move to v2 as there are some memory issues we are encountering in the load_balanced version. 

### What is the proposed change?

Apply similar changes from this commit to v2: https://github.com/nats-io/nats-spark-connector/commit/2f6314d17fab56ba4887509a76fc3b03154d61d7

I would be happy to contribute!

### Who benefits from this change?

Everyone who compresses stream data

### What alternatives have you evaluated?

load_balanced works for the time being, however it runs into memory issues on our machine after ingesting around 4M messages

**Comment by stoddabr** [comment]
Would https://github.com/nats-io/nats-spark-connector/blob/main/V2/nats-spark-connector/src/main/scala/org/apache/spark/sql/nats/NatsSource.scala#L23 be a good place to implement this?

**Comment by jnmoyne** [comment]
Would definitely welcome a contribution for this, indeed using the V1 commit you mention as a model (e.g. use the same config argument name to specify the compression type).

> Would https://github.com/nats-io/nats-spark-connector/blob/main/V2/nats-spark-connector/src/main/scala/org/apache/spark/sql/nats/NatsSource.scala#L23 be a good place to implement this?

Yes, that is the place where the NATS messages (and its JS metadata) are transformed into Spark rows.
